/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
{
"type": "string",
"pattern": "(\\A\\s*(?<lat>[-+]?\\d*\\.?\\d+)\\s*,\\s*(?<lon>[-+]?\\d*\\.?\\d+)\\s*\\z)"
},
{
"type": "string",
"pattern": "(?i-mx:\\A\\s*POINT\\s*\\(\\s*(?<lon>[-+]?\\d*\\.?\\d+)\\s+(?<lat>[-+]?\\d*\\.?\\d+)\\s*\\)\\s*\\z)"
},
{
"type": "string",
"pattern": "(\\A[0-9b-hjkmnp-z]+\\z)"
},
{
"type": "array",
"minItems": 2,
"maxItems": 2,
"additionalProperties": false,
"items": {
"type": "number",
"minimum": -180,
"maximum": 180
}
}
 */

interface GeoPoint {
    fun validate()
}

class LatLonPoint : GeoPoint() {
    constructor(val s: string) {
        TODO("Not yet implemented")
    }

    override fun validate() {
        TODO("Not yet implemented")
    }
}

class PointPoint : GeoPoint() {
    constructor(val s: string) {
        TODO("Not yet implemented")
    }

    override fun validate() {
        val rx = "(?i-mx:\\A\\s*POINT\\s*\\(\\s*(?<lon>[-+]?\\d*\\.?\\d+)\\s+(?<lat>[-+]?\\d*\\.?\\d+)\\s*\\)\\s*\\z)"
    }
}
