/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FilterValue
import org.openapitools.client.models.GeoPoint
import org.openapitools.client.models.GeoUnitEnum

import com.squareup.moshi.Json

/**
 * A range filter with a geographic center
 *
 * @param unit 
 * @param center 
 * @param from 
 * @param to 
 */

data class GeoRangeFilter (

    @Json(name = "unit")
    val unit: GeoUnitEnum,

    @Json(name = "center")
    val center: GeoPoint,

    @Json(name = "from")
    val from: FilterValue? = null,

    @Json(name = "to")
    val to: FilterValue? = null

)

