/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param any 
 * @param all 
 * @param none 
 */

data class ArrayOrSingularFilterClausesOrFilter (

    @Json(name = "any")
    val any: ArrayOrSingularFilterClausesOrFilter? = null,

    @Json(name = "all")
    val all: ArrayOrSingularFilterClausesOrFilter? = null,

    @Json(name = "none")
    val none: ArrayOrSingularFilterClausesOrFilter? = null

)

