/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * Response from a request to create a batch of synonym sets
 *
 * @param hasErrors True if any of the requested synonym sets have errors
 * @param synonymSets The synonym sets requested to be created
 */

data class BatchSynonymSetsResponse (

    /* True if any of the requested synonym sets have errors */
    @Json(name = "has_errors")
    val hasErrors: kotlin.Boolean? = null,

    /* The synonym sets requested to be created */
    @Json(name = "synonym_sets")
    val synonymSets: kotlin.collections.List<CreatedSynonymSetResponse>? = null

)

