/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AnyOfLessThanFilterValueCommaGeoPointGreaterThan

import com.squareup.moshi.Json

/**
 * Field and type of boost with tuning parameters
 *
 * @param center 
 * @param function 
 */

data class BoostItem (

    @Json(name = "center")
    val center: AnyOfLessThanFilterValueCommaGeoPointGreaterThan,

    @Json(name = "function")
    val function: BoostItem.Function

) {

    /**
     * 
     *
     * Values: `value`,functional,proximity
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "value") `value`("value"),
        @Json(name = "functional") functional("functional"),
        @Json(name = "proximity") proximity("proximity");
    }
    /**
     * 
     *
     * Values: linear,exponential,logarithmic,gaussian
     */
    enum class Function(val value: kotlin.String) {
        @Json(name = "linear") linear("linear"),
        @Json(name = "exponential") exponential("exponential"),
        @Json(name = "logarithmic") logarithmic("logarithmic"),
        @Json(name = "gaussian") gaussian("gaussian");
    }
    /**
     * 
     *
     * Values: add,multiply
     */
    enum class Operation(val value: kotlin.String) {
        @Json(name = "add") add("add"),
        @Json(name = "multiply") multiply("multiply");
    }
}

