/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * Returned when an update request partially updated a content source, but failed to fully configure it as requested
 *
 * @param updated 
 * @param errors 
 */

data class ContentSourcePartialUpdateResponse (

    @Json(name = "updated")
    val updated: ContentSource,

    @Json(name = "errors")
    val errors: kotlin.collections.List<kotlin.String>

)

