/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * An indexing rule to index or omit the content for this Content Source
 *
 * @param exclude 
 * @param include 
 * @param filterType 
 */

data class ContentSourceIndexingRule (

    @Json(name = "exclude")
    val exclude: kotlin.String? = null,

    @Json(name = "include")
    val include: kotlin.String? = null,

    @Json(name = "filter_type")
    val filterType: ContentSourceIndexingRule.FilterType? = null

) {

    /**
     * 
     *
     * Values: objectType,pathTemplate,fileExtension
     */
    enum class FilterType(val value: kotlin.String) {
        @Json(name = "object_type") objectType("object_type"),
        @Json(name = "path_template") pathTemplate("path_template"),
        @Json(name = "file_extension") fileExtension("file_extension");
    }
}

