/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 * @param ranges 
 * @param name 
 * @param center 
 * @param unit 
 * @param propertySize 
 * @param sort 
 */

data class FacetItem (

    @Json(name = "type")
    val type: FacetItem.Type,

    @Json(name = "ranges")
    val ranges: kotlin.collections.List<FacetRangeItem>,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "center")
    val center: GeoPoint? = null,

    @Json(name = "unit")
    val unit: GeoUnitEnum? = null,

    @Json(name = "size")
    val propertySize: kotlin.Int? = null,

    @Json(name = "sort")
    val sort: FacetSort? = null

) {

    /**
     * 
     *
     * Values: `value`
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "value") `value`("value");
    }
}

