/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param from The start of the range, inclusive
 * @param to The end of the range, exclusive
 */

data class Range (

    /* The start of the range, inclusive */
    @Json(name = "from")
    val from: kotlin.String? = null,

    /* The end of the range, exclusive */
    @Json(name = "to")
    val to: kotlin.String? = null

)

