/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param username 
 * @param email 
 * @param accessToken 
 */

data class WhoamiResponse (

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "access_token")
    val accessToken: kotlin.String? = null

)

