/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AnyOfLessThanFilterValueCommaGeoPointGreaterThan
import org.openapitools.client.models.BoostProximityRequirementsAnyOf

import com.squareup.moshi.Json

/**
 * 
 *
 * @param center 
 * @param function 
 */

data class BoostProximityRequirements (

    @Json(name = "center")
    val center: AnyOfLessThanFilterValueCommaGeoPointGreaterThan,

    @Json(name = "function")
    val function: BoostProximityRequirements.Function

) {

    /**
     * 
     *
     * Values: linear,exponential,gaussian
     */
    enum class Function(val value: kotlin.String) {
        @Json(name = "linear") linear("linear"),
        @Json(name = "exponential") exponential("exponential"),
        @Json(name = "gaussian") gaussian("gaussian");
    }
}

