/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param `field` 
 * @param queryExpansionPhrases 
 * @param isPerson 
 */

data class ContentSourceEnabledAutomaticQueryRefinement (

    @Json(name = "field")
    val `field`: kotlin.String,

    @Json(name = "query_expansion_phrases")
    val queryExpansionPhrases: kotlin.collections.List<kotlin.String>,

    @Json(name = "is_person")
    val isPerson: kotlin.Boolean

)

