/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ContentSource

import com.squareup.moshi.Json

/**
 * Returned when a create request successfully created a content source, but failed to fully configure it as requested
 *
 * @param created 
 * @param errors 
 */

data class ContentSourcePartialCreateResponse (

    @Json(name = "created")
    val created: ContentSource,

    @Json(name = "errors")
    val errors: kotlin.collections.List<kotlin.String>

)

