/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param `field` 
 * @param enabled 
 * @param displayName 
 * @param transform 
 */

data class ContentSourceFacet (

    @Json(name = "field")
    val `field`: kotlin.String,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "display_name")
    val displayName: kotlin.String? = null,

    @Json(name = "transform")
    val transform: ContentSourceFacet.Transform? = null

) {

    /**
     * 
     *
     * Values: capitalize,titleize,mimeType
     */
    enum class Transform(val value: kotlin.String) {
        @Json(name = "capitalize") capitalize("capitalize"),
        @Json(name = "titleize") titleize("titleize"),
        @Json(name = "mime_type") mimeType("mime_type");
    }
}

