/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FacetRangeItem
import org.openapitools.client.models.GeoPoint
import org.openapitools.client.models.GeoUnitEnum

import com.squareup.moshi.Json

/**
 * Faceting into buckets by a range of values
 *
 * @param type 
 * @param ranges 
 * @param name 
 * @param center 
 * @param unit 
 */

data class FacetRange (

    @Json(name = "type")
    val type: FacetRange.Type,

    @Json(name = "ranges")
    val ranges: kotlin.collections.List<FacetRangeItem>,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "center")
    val center: GeoPoint? = null,

    @Json(name = "unit")
    val unit: GeoUnitEnum? = null

) {

    /**
     * 
     *
     * Values: range
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "range") range("range");
    }
}

