/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ListSynonymSetResponseMeta
import org.openapitools.client.models.SingleSynonymSetResponse

import com.squareup.moshi.Json

/**
 * A list of synonym sets with metadata
 *
 * @param meta 
 * @param results The synonym list results
 */

data class ListSynonymSetResponse (

    @Json(name = "meta")
    val meta: ListSynonymSetResponseMeta? = null,

    /* The synonym list results */
    @Json(name = "results")
    val results: kotlin.collections.List<SingleSynonymSetResponse>? = null

)

