/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SearchFacetResponseItem
import org.openapitools.client.models.SearchFacetResponseItemData

import com.squareup.moshi.Json

/**
 * facets returned from the query
 *
 * @param type 
 * @param `data` array of facets and counts for this field
 */

data class SearchFacetsResponse (

    @Json(name = "type")
    val type: SearchFacetsResponse.Type? = null,

    /* array of facets and counts for this field */
    @Json(name = "data")
    val `data`: kotlin.collections.List<SearchFacetResponseItemData>? = null

) {

    /**
     * 
     *
     * Values: `value`,range
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "value") `value`("value"),
        @Json(name = "range") range("range");
    }
}

