/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Metadata about this specific result item
 *
 * @param source 
 * @param lastUpdated 
 * @param contentSourceId 
 * @param id 
 * @param score 
 */

data class SearchApiResultItemMeta (

    @Json(name = "source")
    val source: kotlin.String? = null,

    @Json(name = "last_updated")
    val lastUpdated: kotlin.String? = null,

    @Json(name = "content_source_id")
    val contentSourceId: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "score")
    val score: java.math.BigDecimal? = null

)

