/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SearchApiQueryRaw
import org.openapitools.client.models.SearchApiQuerySnippet

import com.squareup.moshi.Json

/**
 * 
 *
 * @param raw 
 * @param snippet 
 */

data class SearchApiQueryResultFields (

    @Json(name = "raw")
    val raw: SearchApiQueryRaw? = null,

    @Json(name = "snippet")
    val snippet: SearchApiQuerySnippet? = null

)

