/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * a content source used in the search query
 *
 * @param name 
 * @param serviceType 
 */

data class SearchApiMetaContentSource (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "service_type")
    val serviceType: kotlin.String? = null

)

