/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param jobType 
 * @param status 
 * @param createdAt 
 * @param lastUpdatedAt 
 */

data class SyncJobDefinition (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "job_type")
    val jobType: SyncJobDefinition.JobType,

    @Json(name = "status")
    val status: SyncJobDefinition.Status,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "last_updated_at")
    val lastUpdatedAt: java.time.OffsetDateTime

) {

    /**
     * 
     *
     * Values: full,incremental,delete,permissions
     */
    enum class JobType(val value: kotlin.String) {
        @Json(name = "full") full("full"),
        @Json(name = "incremental") incremental("incremental"),
        @Json(name = "delete") delete("delete"),
        @Json(name = "permissions") permissions("permissions");
    }
    /**
     * 
     *
     * Values: enqueued,running,suspended,failed,complete
     */
    enum class Status(val value: kotlin.String) {
        @Json(name = "enqueued") enqueued("enqueued"),
        @Json(name = "running") running("running"),
        @Json(name = "suspended") suspended("suspended"),
        @Json(name = "failed") failed("failed"),
        @Json(name = "complete") complete("complete");
    }
}

