/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.InterruptSyncCommand
import org.openapitools.client.models.StartSyncCommand

import com.squareup.moshi.Json

/**
 * 
 *
 * @param command 
 * @param forceInterrupt 
 */

data class SyncJobsCommand (

    @Json(name = "command")
    val command: SyncJobsCommand.Command,

    @Json(name = "force_interrupt")
    val forceInterrupt: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: interrupt
     */
    enum class Command(val value: kotlin.String) {
        @Json(name = "interrupt") interrupt("interrupt");
    }
}

