/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Field and direction to sort on
 *
 * @param createdAt 
 * @param updatedAt 
 */

data class SynonymsSort (

    @Json(name = "created_at")
    val createdAt: SynonymsSort.CreatedAt? = null,

    @Json(name = "updated_at")
    val updatedAt: SynonymsSort.UpdatedAt? = null

) {

    /**
     * 
     *
     * Values: asc,desc
     */
    enum class CreatedAt(val value: kotlin.String) {
        @Json(name = "asc") asc("asc"),
        @Json(name = "desc") desc("desc");
    }
    /**
     * 
     *
     * Values: asc,desc
     */
    enum class UpdatedAt(val value: kotlin.String) {
        @Json(name = "asc") asc("asc"),
        @Json(name = "desc") desc("desc");
    }
}

