/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.ContentSourceAutomaticQueryRefinement
import org.elasticsearch.workplacesearch.models.ContentSourceEnabledAutomaticQueryRefinement

import com.squareup.moshi.Json

/**
 * 
 *
 * @param overrides 
 * @param defaults 
 * @param results 
 */

data class AutomaticQueryRefinementDetailsResponse (

    @Json(name = "overrides")
    val overrides: kotlin.collections.List<ContentSourceAutomaticQueryRefinement>,

    @Json(name = "defaults")
    val defaults: kotlin.collections.List<ContentSourceEnabledAutomaticQueryRefinement>,

    @Json(name = "results")
    val results: kotlin.collections.List<ContentSourceEnabledAutomaticQueryRefinement>

)

