/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.BoostFunctionalRequirementsAnyOf

import com.squareup.moshi.Json

/**
 * 
 *
 * @param function 
 */

data class BoostFunctionalRequirements (

    @Json(name = "function")
    val function: BoostFunctionalRequirements.Function

) {

    /**
     * 
     *
     * Values: linear,exponential,logarithmic
     */
    enum class Function(val value: kotlin.String) {
        @Json(name = "linear") linear("linear"),
        @Json(name = "exponential") exponential("exponential"),
        @Json(name = "logarithmic") logarithmic("logarithmic");
    }
}

