/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models


import com.squareup.moshi.Json

/**
 * Definition to upload Workplace Search Custom Source icons
 *
 * @param mainIcon 
 * @param altIcon 
 */

data class ContentSourceIconDefinition (

    @Json(name = "main_icon")
    val mainIcon: kotlin.ByteArray? = null,

    @Json(name = "alt_icon")
    val altIcon: kotlin.ByteArray? = null

)

