/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param duration The average execution time of the last 5 completed jobs, in ISO-8601 format
 * @param nextStart The estimated next execution time
 */

data class ContentSourceScheduleEstimates (

    /* The average execution time of the last 5 completed jobs, in ISO-8601 format */
    @Json(name = "duration")
    val duration: kotlin.String? = null,

    /* The estimated next execution time */
    @Json(name = "next_start")
    val nextStart: kotlin.String? = null

)

