/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

/**
 * Definition to create a Workplace Search Content Source
 * @param name The human readable display name for this Content Source.
 * @param schema
 * @param display
 * @param isSearchable Whether or not this Content Source will be searchable on the search page.
 * @param indexing
 * @param facets
 * @param automaticQueryRefinement
 */
data class ContentSourceCreateDefinition(

    /* The human readable display name for this Content Source. */
    val name: kotlin.String,
    val schema: ContentSourceSchema? = null,
    val display: ContentSourceDisplay? = null,
    /* Whether or not this Content Source will be searchable on the search page. */
    val isSearchable: kotlin.Boolean? = null,
    val indexing: ContentSourceIndexing? = null,
    val facets: ContentSourceFacets? = null,
    val automaticQueryRefinement: ContentSourceAutomaticQueryRefinements? = null
)
