/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models


/**
 * A time window that applies to a specific type of job
 * @param jobType 
 * @param day 
 * @param start The start of the time window, in the format of HH:mm:ssZ
 * @param end The end of the time window, in the format of HH:mm:ssZ
 */
data class ContentSourceJobTypeWindow (

    val jobType: ContentSourceJobTypeWindow.JobType,
    val day: ContentSourceJobTypeWindow.Day,
    /* The start of the time window, in the format of HH:mm:ssZ */
    val start: kotlin.String? = null,
    /* The end of the time window, in the format of HH:mm:ssZ */
    val end: kotlin.String? = null
) {
    /**
    * 
    * Values: FULL,INCREMENTAL,DELETE,PERMISSIONS,ALL
    */
    enum class JobType(val value: kotlin.String){
        FULL("full"),
        INCREMENTAL("incremental"),
        DELETE("delete"),
        PERMISSIONS("permissions"),
        ALL("all");
    }
    /**
    * 
    * Values: SUNDAY,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,ALL
    */
    enum class Day(val value: kotlin.String){
        SUNDAY("sunday"),
        MONDAY("monday"),
        TUESDAY("tuesday"),
        WEDNESDAY("wednesday"),
        THURSDAY("thursday"),
        FRIDAY("friday"),
        SATURDAY("saturday"),
        ALL("all");
    }
}