/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.ContentSourceJobTypeWindow

/**
 * Schedule defining when and how often the content source should be synchronized
 * @param full How often a full data synchronization should be performed, as an ISO-8601 duration
 * @param incremental How often to synchronize new changes, as an ISO-8601 duration
 * @param delete How often to purge deleted documents, as an ISO-8601 duration
 * @param permissions How often to update user permissions, as an ISO-8601 duration
 * @param blockedWindows 
 */
data class ContentSourceSchedule (

    /* How often a full data synchronization should be performed, as an ISO-8601 duration */
    val full: kotlin.String? = null,
    /* How often to synchronize new changes, as an ISO-8601 duration */
    val incremental: kotlin.String? = null,
    /* How often to purge deleted documents, as an ISO-8601 duration */
    val delete: kotlin.String? = null,
    /* How often to update user permissions, as an ISO-8601 duration */
    val permissions: kotlin.String? = null,
    val blockedWindows: kotlin.Array<ContentSourceJobTypeWindow>? = null
) {
}