/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.ContentSourceAutomaticQueryRefinements
import org.elasticsearch.workplacesearch.models.ContentSourceDisplay
import org.elasticsearch.workplacesearch.models.ContentSourceFacets
import org.elasticsearch.workplacesearch.models.ContentSourceIndexingResponse
import org.elasticsearch.workplacesearch.models.SearchGroup

import com.squareup.moshi.Json

/**
 * Workplace Search Content Source
 *
 * @param id The Content Source Identifier.
 * @param serviceType The Content Source's Service Type. For example, for Google Drive the Service Type is \"google_drive\".
 * @param createdAt The date/time at which this Content Source was originally created.
 * @param lastUpdatedAt The date/time at which this Content Source was last updated.
 * @param isRemote Whether or not this Content Source is a \"remote\" content source. See https://www.elastic.co/guide/en/workplace-search/current/workplace-search-content-sources.html#remote
 * @param details A list of key/value metadata for the Content Source and the account which authenticated/connected it.
 * @param groups A list of Workplace Search Group names and IDs which have access to this Content Source.
 * @param name The human readable display name of this Content Source.
 * @param context Can be either \"organization\" or \"private.\" This specifies whether this Content Source is available to groups of users, or a single user.
 * @param isSearchable Whether or not this Content Source can currently be searched over on the search page.
 * @param schema 
 * @param display 
 * @param indexing 
 * @param facets 
 * @param automaticQueryRefinement 
 * @param documentCount How many documents are currently indexed in this Content Source. Note, this field is not applicable to Remote Content Sources.
 * @param lastIndexedAt The date/time when documents were last indexed into this Content Source. This may be \"null\" if documents have not yet been indexed. Note, this field is not applicable to Remote Content Sources.
 */

data class ContentSource (

    /* The Content Source Identifier. */
    @Json(name = "id")
    val id: kotlin.String,

    /* The Content Source's Service Type. For example, for Google Drive the Service Type is \"google_drive\". */
    @Json(name = "service_type")
    val serviceType: kotlin.String,

    /* The date/time at which this Content Source was originally created. */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* The date/time at which this Content Source was last updated. */
    @Json(name = "last_updated_at")
    val lastUpdatedAt: java.time.OffsetDateTime,

    /* Whether or not this Content Source is a \"remote\" content source. See https://www.elastic.co/guide/en/workplace-search/current/workplace-search-content-sources.html#remote */
    @Json(name = "is_remote")
    val isRemote: kotlin.Boolean,

    /* A list of key/value metadata for the Content Source and the account which authenticated/connected it. */
    @Json(name = "details")
    val details: kotlin.collections.List<kotlin.collections.Map<kotlin.String, kotlin.Any>>,

    /* A list of Workplace Search Group names and IDs which have access to this Content Source. */
    @Json(name = "groups")
    val groups: kotlin.collections.List<SearchGroup>,

    /* The human readable display name of this Content Source. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Can be either \"organization\" or \"private.\" This specifies whether this Content Source is available to groups of users, or a single user. */
    @Json(name = "context")
    val context: ContentSource.Context,

    /* Whether or not this Content Source can currently be searched over on the search page. */
    @Json(name = "is_searchable")
    val isSearchable: kotlin.Boolean,

    @Json(name = "schema")
    val schema: ContentSource.Schema? = null,

    @Json(name = "display")
    val display: ContentSourceDisplay? = null,

    @Json(name = "indexing")
    val indexing: ContentSourceIndexingResponse? = null,

    @Json(name = "facets")
    val facets: ContentSourceFacets? = null,

    @Json(name = "automatic_query_refinement")
    val automaticQueryRefinement: ContentSourceAutomaticQueryRefinements? = null,

    /* How many documents are currently indexed in this Content Source. Note, this field is not applicable to Remote Content Sources. */
    @Json(name = "document_count")
    val documentCount: kotlin.Int? = null,

    /* The date/time when documents were last indexed into this Content Source. This may be \"null\" if documents have not yet been indexed. Note, this field is not applicable to Remote Content Sources. */
    @Json(name = "last_indexed_at")
    val lastIndexedAt: java.time.OffsetDateTime? = null

) {

    /**
     * Can be either \"organization\" or \"private.\" This specifies whether this Content Source is available to groups of users, or a single user.
     *
     * Values: organization,`private`
     */
    enum class Context(val value: kotlin.String) {
        @Json(name = "organization") organization("organization"),
        @Json(name = "private") `private`("private");
    }
    /**
     * 
     *
     * Values: text,geolocation,number,date
     */
    enum class Schema(val value: kotlin.String) {
        @Json(name = "text") text("text"),
        @Json(name = "geolocation") geolocation("geolocation"),
        @Json(name = "number") number("number"),
        @Json(name = "date") date("date");
    }
}

