/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models


import com.squareup.moshi.Json

/**
 * A time window that applies to a specific type of job
 *
 * @param jobType 
 * @param day 
 * @param start The start of the time window, as an ISO-8601 duration
 * @param end The end of the time window, as an ISO-8601 duration
 */

data class ContentSourceJobTypeWindow (

    @Json(name = "job_type")
    val jobType: ContentSourceJobTypeWindow.JobType? = null,

    @Json(name = "day")
    val day: ContentSourceJobTypeWindow.Day? = null,

    /* The start of the time window, as an ISO-8601 duration */
    @Json(name = "start")
    val start: kotlin.String? = null,

    /* The end of the time window, as an ISO-8601 duration */
    @Json(name = "end")
    val end: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: full,incremental,delete,permissions,all
     */
    enum class JobType(val value: kotlin.String) {
        @Json(name = "full") full("full"),
        @Json(name = "incremental") incremental("incremental"),
        @Json(name = "delete") delete("delete"),
        @Json(name = "permissions") permissions("permissions"),
        @Json(name = "all") all("all");
    }
    /**
     * 
     *
     * Values: sunday,monday,tuesday,wednesday,thursday,friday,saturday,all
     */
    enum class Day(val value: kotlin.String) {
        @Json(name = "sunday") sunday("sunday"),
        @Json(name = "monday") monday("monday"),
        @Json(name = "tuesday") tuesday("tuesday"),
        @Json(name = "wednesday") wednesday("wednesday"),
        @Json(name = "thursday") thursday("thursday"),
        @Json(name = "friday") friday("friday"),
        @Json(name = "saturday") saturday("saturday"),
        @Json(name = "all") all("all");
    }
}

