/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.ContentSourceScheduleEstimates

import com.squareup.moshi.Json

/**
 * Estimates of when the next sync of each type will be run and average execution time
 *
 * @param full 
 * @param incremental 
 * @param delete 
 * @param permissions 
 */

data class ContentSourceScheduleResponseEstimates (

    @Json(name = "full")
    val full: ContentSourceScheduleEstimates? = null,

    @Json(name = "incremental")
    val incremental: ContentSourceScheduleEstimates? = null,

    @Json(name = "delete")
    val delete: ContentSourceScheduleEstimates? = null,

    @Json(name = "permissions")
    val permissions: ContentSourceScheduleEstimates? = null

)

