/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.ContentSource
import org.elasticsearch.workplacesearch.models.Errors

/**
 * Returned when an update request partially updated a content source, but failed to fully configure it as requested
 * @param updated 
 * @param errors 
 */
data class ContentSourcePartialUpdateResponse (

    val updated: ContentSource,
    val errors: Errors
) {
}