/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

/**
 *
 * @param duration The average execution time of the last 5 completed jobs, in ISO-8601 format
 * @param nextStart The estimated next execution time
 */
data class ContentSourceScheduleEstimates(

    /* The average execution time of the last 5 completed jobs, in ISO-8601 format */
    val duration: kotlin.String? = null,
    /* The estimated next execution time */
    val nextStart: kotlin.String? = null
)
