/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.ContentSourceDisplayDetail

import com.squareup.moshi.Json

/**
 * 
 *
 * @param titleField 
 * @param urlField 
 * @param color 
 * @param descriptionField 
 * @param subtitleField 
 * @param typeField 
 * @param mediaTypeField 
 * @param createdByField 
 * @param updatedByField 
 * @param detailFields 
 */

data class ContentSourceDisplay (

    @Json(name = "title_field")
    val titleField: kotlin.String,

    @Json(name = "url_field")
    val urlField: kotlin.String,

    @Json(name = "color")
    val color: kotlin.String? = null,

    @Json(name = "description_field")
    val descriptionField: kotlin.String? = null,

    @Json(name = "subtitle_field")
    val subtitleField: kotlin.String? = null,

    @Json(name = "type_field")
    val typeField: kotlin.String? = null,

    @Json(name = "media_type_field")
    val mediaTypeField: kotlin.String? = null,

    @Json(name = "created_by_field")
    val createdByField: kotlin.String? = null,

    @Json(name = "updated_by_field")
    val updatedByField: kotlin.String? = null,

    @Json(name = "detail_fields")
    val detailFields: kotlin.collections.List<ContentSourceDisplayDetail>? = null

)

