/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

/**
 * The range for a facet's bucket
 * @param from
 * @param to
 * @param name
 */
data class FacetRangeItem(

    val from: kotlin.Any? = null,
    val to: kotlin.Any? = null,
    val name: kotlin.String? = null
)
