/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.FacetSort

import com.squareup.moshi.Json

/**
 * Facet by a field value
 *
 * @param type 
 * @param name 
 * @param propertySize 
 * @param sort 
 */

data class FacetValue (

    @Json(name = "type")
    val type: FacetValue.Type,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "size")
    val propertySize: kotlin.Int? = null,

    @Json(name = "sort")
    val sort: FacetSort? = null

) {

    /**
     * 
     *
     * Values: `value`
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "value") `value`("value");
    }
}

