/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

/**
 * Faceting into buckets by a range of values
 * @param type
 * @param name
 * @param ranges
 * @param center
 * @param unit
 */
data class FacetRange(

    val type: kotlin.String,
    val name: kotlin.String? = null,
    val ranges: kotlin.Array<FacetRangeItem>,
    val center: GeoPoint? = null,
    val unit: GeoUnitEnum? = null
)
