/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.FilterValue
import org.elasticsearch.workplacesearch.models.GeoPoint
import org.elasticsearch.workplacesearch.models.GeoUnitEnum

/**
 * A range filter with a geographic center
 * @param unit 
 * @param center 
 * @param from 
 * @param to 
 */
data class GeoRangeFilter (

    val unit: GeoUnitEnum,
    val center: GeoPoint,
    val from: FilterValue? = null,
    val to: FilterValue? = null
) {
}