/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.GeoPoint
import org.elasticsearch.workplacesearch.models.GeoUnitEnum

import com.squareup.moshi.Json

/**
 * 
 *
 * @param unit 
 * @param center 
 * @param distance A number representing the distance unit
 */

data class GeoDistanceFilter (

    @Json(name = "unit")
    val unit: GeoUnitEnum,

    @Json(name = "center")
    val center: GeoPoint,

    /* A number representing the distance unit */
    @Json(name = "distance")
    val distance: java.math.BigDecimal

)

