/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models


import com.squareup.moshi.Json

/**
 * Command to interrupt a synchronisation job for Content Source
 *
 * @param command 
 */

data class InterruptSyncCommandAllOf (

    @Json(name = "command")
    val command: InterruptSyncCommandAllOf.Command? = null

) {

    /**
     * 
     *
     * Values: interrupt
     */
    enum class Command(val value: kotlin.String) {
        @Json(name = "interrupt") interrupt("interrupt");
    }
}

