/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.AbstractSyncCommand

/**
 * 
 * @param command 
 */
data class InterruptSyncCommand (

    val command: InterruptSyncCommand.Command
) {
    /**
    * 
    * Values: INTERRUPT
    */
    enum class Command(val value: kotlin.String){
        INTERRUPT("interrupt");
    }
}