/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.ExternalIdentity
import org.elasticsearch.workplacesearch.models.MetaPage

/**
 * 
 * @param meta 
 * @param results 
 */
data class ListExternalIdentitiesResponse (

    val meta: MetaPage,
    val results: kotlin.Array<ExternalIdentity>
) {
}