/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.ListSynonymSetResponseMetaFilter
import org.elasticsearch.workplacesearch.models.ListSynonymSetResponseMetaSort
import org.elasticsearch.workplacesearch.models.MetaPagePage

import com.squareup.moshi.Json

/**
 * 
 *
 * @param page 
 * @param filter 
 * @param sort 
 */

data class ListSynonymSetResponseMeta (

    @Json(name = "page")
    val page: MetaPagePage? = null,

    @Json(name = "filter")
    val filter: ListSynonymSetResponseMetaFilter? = null,

    @Json(name = "sort")
    val sort: ListSynonymSetResponseMetaSort? = null

)

