/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.ListSynonymSetResponseMetaFilter
import org.elasticsearch.workplacesearch.models.ListSynonymSetResponseMetaSort
import org.elasticsearch.workplacesearch.models.MetaPagePage

/**
 * 
 * @param page 
 * @param filter 
 * @param sort 
 */
data class ListSynonymSetResponseMeta (

    val page: MetaPagePage? = null,
    val filter: ListSynonymSetResponseMetaFilter? = null,
    val sort: ListSynonymSetResponseMetaSort? = null
) {
}