/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.OneOfLessThanArrayOrSingularFilterValueCommaRangeFilterCommaGeoRangeFilterCommaGeoDistanceFilterGreaterThan

import com.squareup.moshi.Json

/**
 * Specifics regarding how this part of the query was refined
 *
 * @param term The term(s) used for the trigger
 * @param position The start and end position the term(s) exist in the original query
 * @param triggerType The type of trigger created
 * @param triggerFilterType The type of filter created from this trigger
 * @param filter 
 */

data class QueryRefinementItem (

    /* The term(s) used for the trigger */
    @Json(name = "term")
    val term: kotlin.String? = null,

    /* The start and end position the term(s) exist in the original query */
    @Json(name = "position")
    val position: kotlin.collections.List<java.math.BigDecimal>? = null,

    /* The type of trigger created */
    @Json(name = "trigger_type")
    val triggerType: kotlin.String? = null,

    /* The type of filter created from this trigger */
    @Json(name = "trigger_filter_type")
    val triggerFilterType: kotlin.String? = null,

    @Json(name = "filter")
    val filter: kotlin.collections.Map<kotlin.String, OneOfLessThanArrayOrSingularFilterValueCommaRangeFilterCommaGeoRangeFilterCommaGeoDistanceFilterGreaterThan>? = null

)

