/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models


/**
 * 
 * @param from The start of the range, inclusive
 * @param to The end of the range, exclusive
 */
data class Range (

    /* The start of the range, inclusive */
    val from: kotlin.String? = null,
    /* The end of the range, exclusive */
    val to: kotlin.String? = null
) {
}