/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.QueryRefinementItem

/**
 * Metadata regarding automatic refinements made to the query
 * @param submittedQuery 
 * @param decoratedQueryHtml 
 * @param refinements 
 */
data class SearchApiQueryRefinement (

    val submittedQuery: kotlin.String,
    val decoratedQueryHtml: kotlin.String,
    val refinements: kotlin.Array<QueryRefinementItem>
) {
}