/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.OneOfLessThanStringCommaNumberGreaterThan

import com.squareup.moshi.Json

/**
 * 
 *
 * @param count 
 * @param `value` 
 * @param key 
 * @param from 
 * @param to 
 */

data class SearchFacetResponseItemData (

    @Json(name = "count")
    val count: kotlin.Int,

    @Json(name = "value")
    val `value`: OneOfLessThanStringCommaNumberGreaterThan? = null,

    @Json(name = "key")
    val key: kotlin.String? = null,

    @Json(name = "from")
    val from: OneOfLessThanStringCommaNumberGreaterThan? = null,

    @Json(name = "to")
    val to: OneOfLessThanStringCommaNumberGreaterThan? = null

)

