/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.SearchApiEndpointResponseMeta
import org.elasticsearch.workplacesearch.models.SearchApiResultItem
import org.elasticsearch.workplacesearch.models.SearchFacetsResponse

/**
 * 
 * @param meta 
 * @param results 
 * @param facets 
 */
data class SearchApiEndpointResponse (

    val meta: SearchApiEndpointResponseMeta,
    val results: kotlin.Array<SearchApiResultItem>,
    val facets: SearchFacetsResponse? = null
) {
}