/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.SearchApiResultItemMeta

import com.squareup.moshi.Json

/**
 * A single search result item
 *
 * @param meta 
 */

data class SearchApiResultItem (

    @Json(name = "_meta")
    val meta: SearchApiResultItemMeta? = null

) : kotlin.collections.HashMap<String, kotlin.Any>()

