/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.FilterClausesOrFilter
import org.elasticsearch.workplacesearch.models.SearchApiQueryPage
import org.elasticsearch.workplacesearch.models.SearchApiQueryResultFields
import org.elasticsearch.workplacesearch.models.SearchApiQuerySearchFields

/**
 * 
 * @param query A string or number used to find related documents
 * @param automaticQueryRefinement Set to false to not automatically refine the query by keywords
 * @param page 
 * @param searchFields Restrict the fulltext search to only specific fields
 * @param resultFields Restrict the result fields for each item to the specified fields
 * @param filters 
 * @param sort 
 * @param facets 
 * @param boosts 
 * @param sourceType Optional parameter to search standard, remote only, or all available sources
 * @param timeout Optional timeout in ms for searching remote sources
 * @param contentSources Optional list of content source ids to only return results from
 */
data class SearchApiQuery (

    /* A string or number used to find related documents */
    val query: kotlin.String? = null,
    /* Set to false to not automatically refine the query by keywords */
    val automaticQueryRefinement: kotlin.Boolean? = null,
    val page: SearchApiQueryPage? = null,
    /* Restrict the fulltext search to only specific fields */
    val searchFields: kotlin.collections.Map<kotlin.String, SearchApiQuerySearchFields>? = null,
    /* Restrict the result fields for each item to the specified fields */
    val resultFields: kotlin.collections.Map<kotlin.String, SearchApiQueryResultFields>? = null,
    val filters: FilterClausesOrFilter? = null,
    val sort: OneOfsearchApiQuerySort? = null,
    val facets: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val boosts: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    /* Optional parameter to search standard, remote only, or all available sources */
    val sourceType: kotlin.String? = null,
    /* Optional timeout in ms for searching remote sources */
    val timeout: kotlin.Int? = null,
    /* Optional list of content source ids to only return results from */
    val contentSources: kotlin.Array<kotlin.String>? = null
) {
}