/**
 * Workplace Search API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.elasticsearch.workplacesearch.models

import org.elasticsearch.workplacesearch.models.StartSyncCommandAllOf

import com.squareup.moshi.Json

/**
 * 
 *
 * @param forceInterrupt 
 * @param command 
 */

data class StartSyncCommand (

    @Json(name = "force_interrupt")
    val forceInterrupt: kotlin.Boolean? = null,

    @Json(name = "command")
    val command: StartSyncCommand.Command? = null

) {

    /**
     * 
     *
     * Values: start
     */
    enum class Command(val value: kotlin.String) {
        @Json(name = "start") start("start");
    }
}

