/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

/**
 * Field and direction to sort on
 * @param createdAt
 * @param updatedAt
 */
data class SynonymsSort(

    val createdAt: SynonymsSort.CreatedAt? = null,
    val updatedAt: SynonymsSort.UpdatedAt? = null
) {
    /**
     *
     * Values: ASC,DESC
     */
    enum class CreatedAt(val value: kotlin.String) {
        ASC("asc"),
        DESC("desc");
    }
    /**
     *
     * Values: ASC,DESC
     */
    enum class UpdatedAt(val value: kotlin.String) {
        ASC("asc"),
        DESC("desc");
    }
}
