/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

/**
 * Rules for indexing the content for this Content Source
 * @param enabled
 * @param features
 * @param defaultAction
 * @param rules
 * @param schedule
 */
data class ContentSourceIndexing(

    val enabled: kotlin.Boolean? = null,
    val features: ContentSourceIndexingFeatures? = null,
    val defaultAction: ContentSourceIndexing.DefaultAction,
    val rules: kotlin.Array<ContentSourceIndexingRule>? = null,
    val schedule: ContentSourceSchedule? = null
) {
    /**
     *
     * Values: INCLUDE,EXCLUDE
     */
    enum class DefaultAction(val value: kotlin.String) {
        INCLUDE("include"),
        EXCLUDE("exclude");
    }
}
