/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

/**
 * An indexing rule to index or omit the content for this Content Source
 * @param exclude
 * @param include
 * @param filterType
 */
data class ContentSourceIndexingRule(

    val exclude: kotlin.String? = null,
    val include: kotlin.String? = null,
    val filterType: ContentSourceIndexingRule.FilterType? = null
) {
    /**
     *
     * Values: OBJECTTYPE,PATHTEMPLATE,FILEEXTENSION
     */
    enum class FilterType(val value: kotlin.String) {
        OBJECTTYPE("object_type"),
        PATHTEMPLATE("path_template"),
        FILEEXTENSION("file_extension");
    }
}
