/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

/**
 * A created synonym set with possible error information
 * @param id The id of the created set, or null if invalid
 * @param synonyms The synonym terms for the set
 * @param errors An optional array of error messages, if any
 */
data class CreatedSynonymSetResponse(

    /* The id of the created set, or null if invalid */
    val id: kotlin.String? = null,
    /* The synonym terms for the set */
    val synonyms: kotlin.Array<kotlin.String>? = null,
    /* An optional array of error messages, if any */
    val errors: kotlin.Array<kotlin.String>? = null
)
