/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

/**
 * Facet by a field value
 * @param type
 * @param name
 * @param size
 * @param sort
 */
data class FacetValue(

    val type: kotlin.String,
    val name: kotlin.String? = null,
    val size: kotlin.Int? = null,
    val sort: FacetSort? = null
)
