/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

/**
 * A list of synonym sets with metadata
 * @param meta
 * @param results The synonym list results
 */
data class ListSynonymSetResponse(

    val meta: ListSynonymSetResponseMeta? = null,
    /* The synonym list results */
    val results: kotlin.Array<SingleSynonymSetResponse>? = null
)
