/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

/**
 * Specifics regarding how this part of the query was refined
 * @param term The term(s) used for the trigger
 * @param position The start and end position the term(s) exist in the original query
 * @param triggerType The type of trigger created
 * @param triggerFilterType The type of filter created from this trigger
 * @param filter
 */
data class QueryRefinementItem(

    /* The term(s) used for the trigger */
    val term: kotlin.String? = null,
    /* The start and end position the term(s) exist in the original query */
    val position: kotlin.Array<java.math.BigDecimal>? = null,
    /* The type of trigger created */
    val triggerType: kotlin.String? = null,
    /* The type of filter created from this trigger */
    val triggerFilterType: kotlin.String? = null,
    val filter: Filter? = null
)
