/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplacesearch.models

/**
 * A representation of a synonym set
 * @param id The id of the synonym set
 * @param synonyms The synonym terms for the set
 * @param createdAt The timestamp in ISO format when the set was created
 * @param updatedAt The timestamp in ISO format when the set was last updated
 */
data class SingleSynonymSetResponse(

    /* The id of the synonym set */
    val id: kotlin.String? = null,
    /* The synonym terms for the set */
    val synonyms: kotlin.Array<kotlin.String>? = null,
    /* The timestamp in ISO format when the set was created */
    val createdAt: kotlin.String? = null,
    /* The timestamp in ISO format when the set was last updated */
    val updatedAt: kotlin.String? = null
)
