/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model

import org.elasticsearch.workplace-search.model.ContentSourceAutomaticQueryRefinement
import org.elasticsearch.workplace-search.model.ContentSourceEnabledAutomaticQueryRefinement

/**
 * 
 * @param overrides 
 * @param defaults 
 * @param results 
 */
data class AutomaticQueryRefinementDetailsResponse (

    val overrides: kotlin.Array<ContentSourceAutomaticQueryRefinement>,
    val defaults: kotlin.Array<ContentSourceEnabledAutomaticQueryRefinement>,
    val results: kotlin.Array<ContentSourceEnabledAutomaticQueryRefinement>
) {
}