/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model

import org.elasticsearch.workplace-search.model.BoostFunctionalRequirements
import org.elasticsearch.workplace-search.model.BoostProximityRequirements
import org.elasticsearch.workplace-search.model.BoostValueItemtype
import org.elasticsearch.workplace-search.model.BoostValueRequirements

/**
 * Field and type of boost with tuning parameters
 * @param type 
 * @param value 
 * @param function 
 * @param operation 
 * @param factor 
 * @param center 
 */
data class BoostItem (

    val type: kotlin.String,
    val value: BoostValueItemtype? = null,
    val function: kotlin.String? = null,
    val operation: BoostItem.Operation? = null,
    val factor: java.math.BigDecimal? = null,
    val center: kotlin.Any? = null
) {
    /**
    * 
    * Values: ADD,MULTIPLY
    */
    enum class Operation(val value: kotlin.String){
        ADD("add"),
        MULTIPLY("multiply");
    }
}