/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model

import org.elasticsearch.workplace-search.model.ContentSourceAutomaticQueryRefinements
import org.elasticsearch.workplace-search.model.ContentSourceDetail
import org.elasticsearch.workplace-search.model.ContentSourceDisplay
import org.elasticsearch.workplace-search.model.ContentSourceFacets
import org.elasticsearch.workplace-search.model.ContentSourceIndexingResponse
import org.elasticsearch.workplace-search.model.ContentSourceSchema
import org.elasticsearch.workplace-search.model.SearchGroup

/**
 * Workplace Search Content Source
 * @param id The Content Source Identifier.
 * @param serviceType The Content Source's Service Type. For example, for Google Drive the Service Type is \"google_drive\".
 * @param createdAt The date/time at which this Content Source was originally created.
 * @param lastUpdatedAt The date/time at which this Content Source was last updated.
 * @param isRemote Whether or not this Content Source is a \"remote\" content source. See https://www.elastic.co/guide/en/workplace-search/current/workplace-search-content-sources.html#remote
 * @param details A list of key/value metadata for the Content Source and the account which authenticated/connected it.
 * @param groups A list of Workplace Search Group names and IDs which have access to this Content Source.
 * @param name The human readable display name of this Content Source.
 * @param schema 
 * @param display 
 * @param context Can be either \"organization\" or \"private.\" This specifies whether this Content Source is available to groups of users, or a single user.
 * @param isSearchable Whether or not this Content Source can currently be searched over on the search page.
 * @param indexing 
 * @param facets 
 * @param automaticQueryRefinement 
 * @param documentCount How many documents are currently indexed in this Content Source. Note, this field is not applicable to Remote Content Sources.
 * @param lastIndexedAt The date/time when documents were last indexed into this Content Source. This may be \"null\" if documents have not yet been indexed. Note, this field is not applicable to Remote Content Sources.
 */
data class ContentSource (

    /* The Content Source Identifier. */
    val id: kotlin.String,
    /* The Content Source's Service Type. For example, for Google Drive the Service Type is \"google_drive\". */
    val serviceType: kotlin.String,
    /* The date/time at which this Content Source was originally created. */
    val createdAt: java.time.LocalDateTime,
    /* The date/time at which this Content Source was last updated. */
    val lastUpdatedAt: java.time.LocalDateTime,
    /* Whether or not this Content Source is a \"remote\" content source. See https://www.elastic.co/guide/en/workplace-search/current/workplace-search-content-sources.html#remote */
    val isRemote: kotlin.Boolean,
    /* A list of key/value metadata for the Content Source and the account which authenticated/connected it. */
    val details: kotlin.Array<ContentSourceDetail>,
    /* A list of Workplace Search Group names and IDs which have access to this Content Source. */
    val groups: kotlin.Array<SearchGroup>,
    /* The human readable display name of this Content Source. */
    val name: kotlin.String,
    val schema: ContentSourceSchema? = null,
    val display: ContentSourceDisplay? = null,
    /* Can be either \"organization\" or \"private.\" This specifies whether this Content Source is available to groups of users, or a single user. */
    val context: ContentSource.Context,
    /* Whether or not this Content Source can currently be searched over on the search page. */
    val isSearchable: kotlin.Boolean,
    val indexing: ContentSourceIndexingResponse? = null,
    val facets: ContentSourceFacets? = null,
    val automaticQueryRefinement: ContentSourceAutomaticQueryRefinements? = null,
    /* How many documents are currently indexed in this Content Source. Note, this field is not applicable to Remote Content Sources. */
    val documentCount: kotlin.Int? = null,
    /* The date/time when documents were last indexed into this Content Source. This may be \"null\" if documents have not yet been indexed. Note, this field is not applicable to Remote Content Sources. */
    val lastIndexedAt: kotlin.Any? = null
) {
    /**
    * Can be either \"organization\" or \"private.\" This specifies whether this Content Source is available to groups of users, or a single user.
    * Values: ORGANIZATION,PRIVATE
    */
    enum class Context(val value: kotlin.String){
        ORGANIZATION("organization"),
        PRIVATE("private");
    }
}