/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model

import org.elasticsearch.workplace-search.model.ContentSource
import org.elasticsearch.workplace-search.model.Errors

/**
 * Returned when a create request successfully created a content source, but failed to fully configure it as requested
 * @param created 
 * @param errors 
 */
data class ContentSourcePartialCreateResponse (

    val created: ContentSource,
    val errors: Errors
) {
}