/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model

import org.elasticsearch.workplace-search.model.ContentSourceScheduleEstimates

/**
 * Estimates of when the next sync of each type will be run and average execution time
 * @param full 
 * @param incremental 
 * @param delete 
 * @param permissions 
 */
data class ContentSourceScheduleResponseEstimates (

    val full: ContentSourceScheduleEstimates? = null,
    val incremental: ContentSourceScheduleEstimates? = null,
    val delete: ContentSourceScheduleEstimates? = null,
    val permissions: ContentSourceScheduleEstimates? = null
) {
}