/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model

import org.elasticsearch.workplace-search.model.ContentSourceDisplayDetail

/**
 * 
 * @param titleField 
 * @param urlField 
 * @param color 
 * @param descriptionField 
 * @param subtitleField 
 * @param typeField 
 * @param mediaTypeField 
 * @param createdByField 
 * @param updatedByField 
 * @param detailFields 
 */
data class ContentSourceDisplay (

    val titleField: kotlin.String,
    val urlField: kotlin.String,
    val color: kotlin.String? = null,
    val descriptionField: kotlin.Any? = null,
    val subtitleField: kotlin.Any? = null,
    val typeField: kotlin.Any? = null,
    val mediaTypeField: kotlin.Any? = null,
    val createdByField: kotlin.Any? = null,
    val updatedByField: kotlin.Any? = null,
    val detailFields: kotlin.Array<ContentSourceDisplayDetail>? = null
) {
}