/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model

import org.elasticsearch.workplace-search.model.ArrayOrSingularFilterClausesOrFilter

/**
 * 
 * @param any 
 * @param all 
 * @param none 
 */
data class FilterClauses (

    val any: ArrayOrSingularFilterClausesOrFilter? = null,
    val all: ArrayOrSingularFilterClausesOrFilter? = null,
    val none: ArrayOrSingularFilterClausesOrFilter? = null
) {
}