/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model


/**
 * 
 * Values: M,MI,IN,FT,YD,KM,CM,MM
 */
enum class GeoUnitEnum(val value: kotlin.String){
    M("m"),// :/
    MI("mi"),// :/
    IN("in"),// :/
    FT("ft"),// :/
    YD("yd"),// :/
    KM("km"),// :/
    CM("cm"),// :/
    MM("mm");// :/
}