/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model

import org.elasticsearch.workplace-search.model.GeoPoint
import org.elasticsearch.workplace-search.model.GeoUnitEnum

/**
 * 
 * @param unit 
 * @param center 
 * @param distance A number representing the distance unit
 */
data class GeoDistanceFilter (

    val unit: GeoUnitEnum,
    val center: GeoPoint,
    /* A number representing the distance unit */
    val distance: java.math.BigDecimal
) {
}