/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model


/**
 * Any sorting applied to the result set
 * @param createdAt 
 * @param updatedAt 
 */
data class ListSynonymSetResponseMetaSort (

    val createdAt: kotlin.String? = null,
    val updatedAt: kotlin.String? = null
) {
}