/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model


/**
 * 
 * @param current 
 * @param totalPages 
 * @param totalResults 
 * @param size 
 */
data class MetaPagePage (

    val current: kotlin.Int,
    val totalPages: kotlin.Int,
    val totalResults: kotlin.Int,
    val size: kotlin.Int
) {
}