/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model

import org.elasticsearch.workplace-search.model.MetaPagePage
import org.elasticsearch.workplace-search.model.SearchApiMetaContentSources
import org.elasticsearch.workplace-search.model.SearchApiQueryRefinement

/**
 * 
 * @param page 
 * @param requestId Internal request ID for this query instance
 * @param warnings Any warnings that the query generated
 * @param queryRefinements 
 * @param contentSources 
 * @param timeout Remote source query timeout value used
 */
data class SearchApiEndpointResponseMeta (

    val page: MetaPagePage,
    /* Internal request ID for this query instance */
    val requestId: kotlin.String,
    /* Any warnings that the query generated */
    val warnings: kotlin.Array<kotlin.String>? = null,
    val queryRefinements: SearchApiQueryRefinement? = null,
    val contentSources: SearchApiMetaContentSources? = null,
    /* Remote source query timeout value used */
    val timeout: kotlin.Int? = null
) {
}