/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model


/**
 * a content source used in the search query
 * @param name 
 * @param serviceType 
 */
data class SearchApiMetaContentSource (

    val name: kotlin.String? = null,
    val serviceType: kotlin.String? = null
) {
}