/**
 * Workplace Search API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.elasticsearch.workplace-search.model

import org.elasticsearch.workplace-search.model.SearchFacetResponseItemData

/**
 * A single facet that was returned from the query
 * @param type 
 * @param &#x60;data&#x60; array of facets and counts for this field
 */
data class SearchFacetResponseItem (

    val type: SearchFacetResponseItem.Type? = null,
    /* array of facets and counts for this field */
    val `data`: kotlin.Array<SearchFacetResponseItemData>? = null
) {
    /**
    * 
    * Values: VALUE,RANGE
    */
    enum class Type(val value: kotlin.String){
        VALUE("value"),
        RANGE("range");
    }
}